"""
Management command: seed_products
Copies product images from static/images/ to media/products/ and creates
Product DB records for all original Malola catalogue items.

Usage:
    python manage.py seed_products
    python manage.py seed_products --clear   # delete existing products first
"""
import shutil
from pathlib import Path
from django.core.management.base import BaseCommand
from django.conf import settings
from store.models import Product, Category

STATIC_IMG = settings.BASE_DIR / 'static' / 'images'
MEDIA_PROD = settings.MEDIA_ROOT / 'products'


def _copy(src_name):
    """Copy src image to media/products/ and return the relative media path."""
    src = STATIC_IMG / src_name
    if not src.exists():
        return ''
    dest = MEDIA_PROD / src_name
    MEDIA_PROD.mkdir(parents=True, exist_ok=True)
    if not dest.exists():
        shutil.copy2(src, dest)
    return f'products/{src_name}'


PRODUCTS = [
    # ── Our Products ────────────────────────────────────────────────────────
    {
        'title':             'Choco Bytes',
        'slug':              'chocobytes',
        'category':          'our_products',
        'price':             199,
        'image_file':        'Choco Bytes Front.png',
        'card_bg':           '#faf3e8',
        'badge':             'BESTSELLER',
        'badge_color':       '#c62828',
        'short_description': 'Crunchy millet bites with a rich chocolate coating',
        'product_type':      'Bites & Crunchies',
        'weights':           '100g,200g',
        'ingredients':       'Whole Millet, Jaggery, Cocoa Powder, Coconut Oil',
        'nut_calories':      '420 kcal',
        'nut_protein':       '8g',
        'nut_fat':           '12g',
        'nut_carbs':         '68g',
        'nut_fibre':         '4g',
        'stock_quantity':    50,
        'country_of_origin': 'India',
        'shelf_life':        '6 months',
    },
    {
        'title':             'Butter Makhana',
        'slug':              'buttermakhana',
        'category':          'our_products',
        'price':             249,
        'image_file':        'butter makhana front.png',
        'card_bg':           '#f5faf0',
        'badge':             'HEALTHY',
        'badge_color':       '#2e7d32',
        'short_description': 'Light roasted fox nuts with real butter flavour',
        'product_type':      'Healthy Snack',
        'weights':           '50g,100g,200g',
        'ingredients':       'Fox Nuts (Makhana), Butter, Rock Salt, Black Pepper',
        'nut_calories':      '347 kcal',
        'nut_protein':       '9g',
        'nut_fat':           '4g',
        'nut_carbs':         '76g',
        'nut_fibre':         '3g',
        'stock_quantity':    60,
        'country_of_origin': 'India',
        'shelf_life':        '6 months',
    },
    {
        'title':             'Banana Granola',
        'slug':              'bananagranola',
        'category':          'our_products',
        'price':             349,
        'image_file':        'Banana Granola.png',
        'card_bg':           '#fdf9ef',
        'badge':             '',
        'short_description': 'Crunchy oat granola with real banana chips and honey',
        'product_type':      'Granola',
        'weights':           '250g,500g',
        'ingredients':       'Rolled Oats, Banana Chips, Honey, Sunflower Seeds, Almonds',
        'nut_calories':      '380 kcal',
        'nut_protein':       '7g',
        'nut_fat':           '10g',
        'nut_carbs':         '64g',
        'nut_fibre':         '5g',
        'stock_quantity':    40,
        'country_of_origin': 'India',
        'shelf_life':        '6 months',
    },
    {
        'title':             'Choco Delight Muesli',
        'slug':              'chocomuesli',
        'category':          'our_products',
        'price':             299,
        'image_file':        'Choco Delight Muesli.png',
        'card_bg':           '#fdf0e8',
        'badge':             '',
        'short_description': 'Wholesome muesli with cocoa bits and mixed grains',
        'product_type':      'Muesli',
        'weights':           '250g,500g',
        'ingredients':       'Rolled Oats, Wheat Flakes, Cocoa Bits, Raisins, Almonds',
        'nut_calories':      '360 kcal',
        'nut_protein':       '9g',
        'nut_fat':           '7g',
        'nut_carbs':         '66g',
        'nut_fibre':         '6g',
        'stock_quantity':    35,
        'country_of_origin': 'India',
        'shelf_life':        '9 months',
    },
    {
        'title':             'Blueberry Pancake Mix',
        'slug':              'blueberrypancake',
        'category':          'our_products',
        'price':             249,
        'image_file':        'Blueberry Pancake.png',
        'card_bg':           '#ede8fb',
        'badge':             '',
        'short_description': 'Quick-mix whole grain pancake batter with blueberry',
        'product_type':      'Pancake Mix',
        'weights':           '150g,300g',
        'ingredients':       'Whole Wheat Flour, Oat Flour, Dried Blueberry, Baking Powder',
        'nut_calories':      '340 kcal',
        'nut_protein':       '8g',
        'nut_fat':           '4g',
        'nut_carbs':         '70g',
        'nut_fibre':         '3g',
        'stock_quantity':    45,
        'country_of_origin': 'India',
        'shelf_life':        '9 months',
    },
    {
        'title':             'Choco Pancake Mix',
        'slug':              'chocopancake',
        'category':          'our_products',
        'price':             249,
        'image_file':        'Choco Pancake Front.png',
        'card_bg':           '#fdf0e8',
        'badge':             '',
        'short_description': 'Rich chocolate flavoured whole grain pancake mix',
        'product_type':      'Pancake Mix',
        'weights':           '150g,300g',
        'ingredients':       'Whole Wheat Flour, Cocoa Powder, Jaggery, Baking Powder',
        'nut_calories':      '350 kcal',
        'nut_protein':       '8g',
        'nut_fat':           '5g',
        'nut_carbs':         '68g',
        'nut_fibre':         '4g',
        'stock_quantity':    45,
        'country_of_origin': 'India',
        'shelf_life':        '9 months',
    },
    {
        'title':             'Moringa Soup Mix',
        'slug':              'moringasoup',
        'category':          'our_products',
        'price':             249,
        'image_file':        'Morniga Soup Front.png',
        'card_bg':           '#edf5e1',
        'badge':             '',
        'short_description': 'Nutrient-rich moringa & lentil instant soup mix',
        'product_type':      'Soup Mix',
        'weights':           '100g,200g',
        'ingredients':       'Moringa Leaf Powder, Red Lentils, Spices, Rock Salt',
        'nut_calories':      '280 kcal',
        'nut_protein':       '14g',
        'nut_fat':           '3g',
        'nut_carbs':         '50g',
        'nut_fibre':         '8g',
        'stock_quantity':    30,
        'country_of_origin': 'India',
        'shelf_life':        '12 months',
    },
    {
        'title':             'Dates Powder',
        'slug':              'datespowder',
        'category':          'our_products',
        'price':             299,
        'image_file':        'Dates Powder.png',
        'card_bg':           '#fdf5e4',
        'badge':             'SUGAR-FREE ALT',
        'badge_color':       '#1565C0',
        'short_description': 'Pure spray-dried dates powder — natural sweetener',
        'product_type':      'Health Powder',
        'weights':           '100g,250g,500g',
        'ingredients':       'Dates (100%)',
        'nut_calories':      '282 kcal',
        'nut_protein':       '2g',
        'nut_fat':           '0.4g',
        'nut_carbs':         '75g',
        'nut_fibre':         '8g',
        'stock_quantity':    50,
        'country_of_origin': 'India',
        'shelf_life':        '12 months',
    },
    {
        'title':             'Millet Noodles',
        'slug':              'milletnoodles',
        'category':          'our_products',
        'price':             199,
        'image_file':        'noodles front.png',
        'card_bg':           '#fdf8ef',
        'badge':             '',
        'short_description': 'Healthy millet-based instant noodles, no maida',
        'product_type':      'Noodles',
        'weights':           '180g,360g',
        'ingredients':       'Foxtail Millet, Tapioca Starch, Salt',
        'nut_calories':      '350 kcal',
        'nut_protein':       '7g',
        'nut_fat':           '2g',
        'nut_carbs':         '76g',
        'nut_fibre':         '3g',
        'stock_quantity':    55,
        'country_of_origin': 'India',
        'shelf_life':        '12 months',
    },
    {
        'title':             'Puff Cheddar Cheese',
        'slug':              'cheddarcheesepuff',
        'category':          'our_products',
        'price':             149,
        'image_file':        'Puff Cheddar Cheese.png',
        'card_bg':           '#fffbf0',
        'badge':             '',
        'short_description': 'Crunchy millet puffs with real cheddar cheese flavour',
        'product_type':      'Puffs',
        'weights':           '50g,100g',
        'ingredients':       'Millet, Cheese Flavour, Salt, Sunflower Oil',
        'nut_calories':      '430 kcal',
        'nut_protein':       '6g',
        'nut_fat':           '18g',
        'nut_carbs':         '62g',
        'nut_fibre':         '2g',
        'stock_quantity':    70,
        'country_of_origin': 'India',
        'shelf_life':        '6 months',
    },
    {
        'title':             'Puff Tangi Tomato',
        'slug':              'tangitomatopuff',
        'category':          'our_products',
        'price':             149,
        'image_file':        'Puff Tangi Tomato.png',
        'card_bg':           '#fff4f0',
        'badge':             '',
        'short_description': 'Tangy tomato flavoured crunchy millet puffs',
        'product_type':      'Puffs',
        'weights':           '50g,100g',
        'ingredients':       'Millet, Tomato Powder, Spices, Salt, Sunflower Oil',
        'nut_calories':      '425 kcal',
        'nut_protein':       '6g',
        'nut_fat':           '17g',
        'nut_carbs':         '63g',
        'nut_fibre':         '2g',
        'stock_quantity':    70,
        'country_of_origin': 'India',
        'shelf_life':        '6 months',
    },
    {
        'title':             'Pirandai Soup Mix',
        'slug':              'pirandaisoup',
        'category':          'our_products',
        'price':             249,
        'image_file':        'Pirandai Soup Front.png',
        'card_bg':           '#eef8f0',
        'badge':             'AYURVEDIC',
        'badge_color':       '#2e7d32',
        'short_description': 'Traditional Pirandai (Cissus) herb soup mix for joints',
        'product_type':      'Soup Mix',
        'weights':           '100g,200g',
        'ingredients':       'Pirandai Powder, Lentils, Spices, Rock Salt',
        'nut_calories':      '270 kcal',
        'nut_protein':       '13g',
        'nut_fat':           '2g',
        'nut_carbs':         '52g',
        'nut_fibre':         '7g',
        'stock_quantity':    25,
        'country_of_origin': 'India',
        'shelf_life':        '12 months',
    },
    {
        'title':             'Mudavattukal Soup Mix',
        'slug':              'mudavattukalsoup',
        'category':          'our_products',
        'price':             249,
        'image_file':        'Mudavattukal Soup Front.png',
        'card_bg':           '#f0f7ee',
        'badge':             'AYURVEDIC',
        'badge_color':       '#2e7d32',
        'short_description': 'Traditional Mudavattukal herb soup for immunity',
        'product_type':      'Soup Mix',
        'weights':           '100g,200g',
        'ingredients':       'Mudavattukal Powder, Lentils, Spices, Rock Salt',
        'nut_calories':      '265 kcal',
        'nut_protein':       '12g',
        'nut_fat':           '2g',
        'nut_carbs':         '51g',
        'nut_fibre':         '7g',
        'stock_quantity':    25,
        'country_of_origin': 'India',
        'shelf_life':        '12 months',
    },
    {
        'title':             'Fruit and Nut Muesli',
        'slug':              'fruitnutmuesli',
        'category':          'our_products',
        'price':             329,
        'image_file':        'Fruit and Nut muesli.png',
        'card_bg':           '#fdf9ef',
        'badge':             '',
        'short_description': 'Hearty muesli loaded with mixed dried fruits and nuts',
        'product_type':      'Muesli',
        'weights':           '250g,500g',
        'ingredients':       'Rolled Oats, Raisins, Almonds, Cashews, Dried Cranberry, Sunflower Seeds',
        'nut_calories':      '370 kcal',
        'nut_protein':       '10g',
        'nut_fat':           '11g',
        'nut_carbs':         '60g',
        'nut_fibre':         '6g',
        'stock_quantity':    40,
        'country_of_origin': 'India',
        'shelf_life':        '9 months',
    },
    # ── New Arrivals ─────────────────────────────────────────────────────────
    {
        'title':             'Millet Vanilla Snack',
        'slug':              'milletvanilla',
        'category':          'new_arrival',
        'price':             299,
        'image_file':        'green.png',
        'card_bg':           '#edf5e1',
        'badge':             'NEW ✨',
        'badge_color':       '#1565C0',
        'short_description': 'Vanilla-flavoured crunchy millet snack bar',
        'product_type':      'Millet Snack',
        'weights':           '100g,200g',
        'ingredients':       'Whole Millet, Vanilla Extract, Jaggery, Coconut Oil',
        'nut_calories':      '410 kcal',
        'nut_protein':       '7g',
        'nut_fat':           '10g',
        'nut_carbs':         '70g',
        'nut_fibre':         '4g',
        'stock_quantity':    30,
        'country_of_origin': 'India',
        'shelf_life':        '6 months',
    },
    {
        'title':             'Millet Choco Snack',
        'slug':              'milletchoco',
        'category':          'new_arrival',
        'price':             299,
        'image_file':        'a6bf2fb7-be25-4e5c-94f4-ba9215f70999_removalai_preview.png',
        'card_bg':           '#f5ede6',
        'badge':             'NEW ✨',
        'badge_color':       '#1565C0',
        'short_description': 'Chocolate-coated crunchy millet snack bar',
        'product_type':      'Millet Snack',
        'weights':           '100g,200g',
        'ingredients':       'Whole Millet, Cocoa Powder, Jaggery, Coconut Oil',
        'nut_calories':      '420 kcal',
        'nut_protein':       '8g',
        'nut_fat':           '11g',
        'nut_carbs':         '68g',
        'nut_fibre':         '4g',
        'stock_quantity':    30,
        'country_of_origin': 'India',
        'shelf_life':        '6 months',
    },
    {
        'title':             'Quinoa Puffs',
        'slug':              'quinoapuffs',
        'category':          'new_arrival',
        'price':             199,
        'image_file':        'red.png',
        'card_bg':           '#fdf0e2',
        'badge':             'NEW ✨',
        'badge_color':       '#1565C0',
        'short_description': 'Light and airy quinoa puffs with a spicy kick',
        'product_type':      'Puffs',
        'weights':           '50g,100g',
        'ingredients':       'Quinoa, Tapioca Starch, Spices, Salt',
        'nut_calories':      '390 kcal',
        'nut_protein':       '9g',
        'nut_fat':           '8g',
        'nut_carbs':         '70g',
        'nut_fibre':         '3g',
        'stock_quantity':    35,
        'country_of_origin': 'India',
        'shelf_life':        '6 months',
    },
]


class Command(BaseCommand):
    help = 'Seed all original Malola catalogue products into the database'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Delete all existing products before seeding',
        )

    def handle(self, *args, **options):
        if options['clear']:
            count = Product.objects.count()
            Product.objects.all().delete()
            self.stdout.write(self.style.WARNING(f'Deleted {count} existing products.'))

        created = 0
        skipped = 0

        for data in PRODUCTS:
            if Product.objects.filter(slug=data['slug']).exists():
                self.stdout.write(f"  SKIP  {data['title']} (already exists)")
                skipped += 1
                continue

            image_path = _copy(data['image_file'])
            if not image_path:
                self.stdout.write(
                    self.style.WARNING(f"  WARN  {data['title']} — image not found: {data['image_file']}")
                )

            Product.objects.create(
                title=data['title'],
                slug=data['slug'],
                category=data['category'],
                price=data['price'],
                image=image_path,
                card_bg=data.get('card_bg', '#f4f7ff'),
                badge=data.get('badge', ''),
                badge_color=data.get('badge_color', '#1565C0'),
                short_description=data.get('short_description', ''),
                description=data.get('short_description', data['title']),
                product_type=data.get('product_type', ''),
                weights=data.get('weights', '100g'),
                ingredients=data.get('ingredients', ''),
                nut_calories=data.get('nut_calories', ''),
                nut_protein=data.get('nut_protein', ''),
                nut_fat=data.get('nut_fat', ''),
                nut_carbs=data.get('nut_carbs', ''),
                nut_fibre=data.get('nut_fibre', ''),
                stock_quantity=data.get('stock_quantity', 50),
                country_of_origin=data.get('country_of_origin', 'India'),
                shelf_life=data.get('shelf_life', '6 months'),
                is_active=True,
            )
            self.stdout.write(self.style.SUCCESS(f"  CREATE {data['title']}"))
            created += 1

        self.stdout.write('')
        self.stdout.write(self.style.SUCCESS(
            f'Done — {created} products created, {skipped} skipped (already existed).'
        ))
