# Generated by Django 6.0.5 on 2026-06-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL id, e.g. choco-bytes', max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('our_products', 'Our Products'), ('new_arrival', 'New Arrival')], default='our_products', max_length=20)),
                ('badge', models.CharField(blank=True, help_text='Badge text e.g. NEW ✨', max_length=50)),
                ('badge_color', models.CharField(blank=True, default='#1565C0', max_length=20)),
                ('card_bg', models.CharField(blank=True, default='#f4f7ff', help_text='Image area background colour', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
