# Generated by Django 6.0.5 on 2026-06-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Comma-separated e.g. Whole Millet, Jaggery, Cocoa'),
        ),
        migrations.AddField(
            model_name='product',
            name='nut_calories',
            field=models.CharField(blank=True, max_length=50, verbose_name='Calories (per 100g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nut_carbs',
            field=models.CharField(blank=True, max_length=50, verbose_name='Carbs'),
        ),
        migrations.AddField(
            model_name='product',
            name='nut_fat',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fat'),
        ),
        migrations.AddField(
            model_name='product',
            name='nut_fibre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fibre'),
        ),
        migrations.AddField(
            model_name='product',
            name='nut_protein',
            field=models.CharField(blank=True, max_length=50, verbose_name='Protein'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, help_text='e.g. Bites & Crunchies', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='weights',
            field=models.CharField(default='100g,200g,500g', help_text='Comma-separated e.g. 100g,200g,500g', max_length=200),
        ),
    ]
