# Generated by Django 6.0.5 on 2026-06-06 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_ingredients_product_nut_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_pct', models.IntegerField(default=0, help_text='Discount 0-100%')),
                ('badge_label', models.CharField(blank=True, help_text='e.g. SALE 20% OFF', max_length=60)),
                ('badge_color', models.CharField(default='#c62828', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.offergroup'),
        ),
    ]
