# Generated by Django 6.0.5 on 2026-06-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_coupon_order_coupon_code_order_discount_amount_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nut_saturated_fat',
            field=models.CharField(blank=True, max_length=50, verbose_name='Saturated Fat'),
        ),
        migrations.AddField(
            model_name='product',
            name='nut_trans_fat',
            field=models.CharField(blank=True, max_length=50, verbose_name='Trans Fat'),
        ),
    ]
