# Generated by Django 6.0.6 on 2026-06-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated filter tags e.g. Kids, Sugar Free, Ragi, Protein Rich'),
        ),
    ]
