# Generated by Django 6.0.6 on 2026-06-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_order_qty',
            field=models.PositiveIntegerField(default=0, help_text='Max units of this product per order. 0 = no limit.'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='If on, stock_quantity is enforced (0 = out of stock). If off, unlimited stock.'),
        ),
    ]
