# Generated by Django 6.0.6 on 2026-06-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_orderstatuslog_order_coupon_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=5, help_text='GST %% (prices are GST-inclusive). Snacks are usually 5, 12 or 18.', max_digits=5),
        ),
    ]
