# Generated by Django 6.0.6 on 2026-06-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_gst_amount_order_subtotal_product_gst_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid Online'), ('cod', 'Cash on Delivery'), ('failed', 'Payment Failed'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('refund_failed', 'Refund Failed — Manual Review')], default='pending', max_length=20),
        ),
    ]
