# Generated by Django 6.0.6 on 2026-06-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_refunded_amount_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Card image shown on the homepage category section', null=True, upload_to='categories/'),
        ),
    ]
