# Generated by Django 6.0.6 on 2026-06-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_add_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True, help_text='If on, stock_quantity is enforced (0 = out of stock). If off, unlimited stock.'),
        ),
    ]
