"""
Django settings for malola_site project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ── Load .env file (if present) ───────────────────────────────────────────────
# Values in .env are only used as fallbacks — real env vars always win.
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    with open(_env_file) as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith('#') and '=' in _line:
                _k, _, _v = _line.partition('=')
                os.environ.setdefault(_k.strip(), _v.strip())

# ── Core settings (all read from environment) ─────────────────────────────────
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

_raw_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(',') if h.strip()]
if not ALLOWED_HOSTS and DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
# Auto-include Railway's public domain if running on Railway
_railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
if _railway_domain and _railway_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_domain)
# When running on Railway, also trust all *.railway.app subdomains (covers the
# internal healthcheck host + the public domain even before one is generated).
# Without this, DEBUG=False + no custom domain => empty ALLOWED_HOSTS => the
# platform healthcheck gets a 400 and the deploy is marked failed.
_on_railway = any(k.startswith('RAILWAY_') for k in os.environ)
if _on_railway:
    for _h in ('.railway.app', 'healthcheck.railway.app', '127.0.0.1'):
        if _h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_h)
# Auto-include Render's public domain if running on Render
_render_domain = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')
if _render_domain and _render_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_domain)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'accounts',
    'notifications',
    'shipping',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'malola_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'malola_site.wsgi.application'


# Database — PostgreSQL
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use DATABASE_URL (Railway/Heroku style) if set, otherwise SQLite for local dev.
_db_url = os.environ.get('DATABASE_URL', '')
if _db_url:
    import urllib.parse as _up
    _p = _up.urlparse(_db_url)
    DATABASES = {
        'default': {
            'ENGINE':       'django.db.backends.postgresql',
            'NAME':         _up.unquote(_p.path.lstrip('/')),
            'USER':         _up.unquote(_p.username or ''),
            'PASSWORD':     _up.unquote(_p.password or ''),
            'HOST':         _p.hostname or 'localhost',
            'PORT':         str(_p.port or 5432),
            'CONN_MAX_AGE': 600,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME':   BASE_DIR / 'db.sqlite3',
        }
    }


# Cache — database-backed so it is shared across all gunicorn workers (the
# default per-process LocMemCache breaks the admin OTP gate under >1 worker).
# Table is created by `manage.py createcachetable` in build.sh.
CACHES = {
    'default': {
        'BACKEND':  'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
}

MEDIA_URL = '/media/'
# Where uploaded files (product images/videos, etc.) are stored. On Railway/Render
# the container disk is wiped on every redeploy, so in production point this at a
# mounted persistent Volume via DJANGO_MEDIA_ROOT (e.g. /data/media). Locally it
# falls back to the project's media/ folder.
MEDIA_ROOT = os.environ.get('DJANGO_MEDIA_ROOT', BASE_DIR / 'media')

# ── Razorpay ──────────────────────────────────────────────────────────────────
RAZORPAY_KEY_ID         = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET     = os.environ.get('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')

# ── Email ─────────────────────────────────────────────────────────────────────
# Many hosts (e.g. Railway's trial plan) block outbound SMTP ports entirely, so
# SMTP-based email just hangs. If BREVO_API_KEY is set we send via Brevo's HTTPS
# API (port 443) through django-anymail instead. Otherwise fall back to SMTP
# (prod) or the console backend (local dev).
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.environ.get('DEFAULT_FROM_EMAIL', f'Malola <{EMAIL_HOST_USER}>')

BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '')
if BREVO_API_KEY:
    EMAIL_BACKEND = 'anymail.backends.brevo.EmailBackend'
    ANYMAIL = {'BREVO_API_KEY': BREVO_API_KEY, 'REQUESTS_TIMEOUT': 15}
else:
    EMAIL_BACKEND = os.environ.get(
        'EMAIL_BACKEND',
        'django.core.mail.backends.console.EmailBackend',   # dev: prints to console
    )
EMAIL_HOST    = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT    = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 15))   # never hang forever on SMTP

# ── Fast2SMS (SMS notifications) ──────────────────────────────────────────────
FAST2SMS_API_KEY = os.environ.get('FAST2SMS_API_KEY', '')

# ── Shiprocket (logistics) ────────────────────────────────────────────────────
SHIPROCKET_EMAIL           = os.environ.get('SHIPROCKET_EMAIL', '')
SHIPROCKET_PASSWORD        = os.environ.get('SHIPROCKET_PASSWORD', '')
SHIPROCKET_PICKUP_LOCATION = os.environ.get('SHIPROCKET_PICKUP_LOCATION', 'Primary')
SHIPROCKET_PICKUP_PINCODE  = os.environ.get('SHIPROCKET_PICKUP_PINCODE', '600001')
SHIPROCKET_DEFAULT_CITY    = os.environ.get('SHIPROCKET_DEFAULT_CITY', 'Chennai')
SHIPROCKET_DEFAULT_STATE   = os.environ.get('SHIPROCKET_DEFAULT_STATE', 'Tamil Nadu')
SHIPROCKET_DEFAULT_PINCODE = os.environ.get('SHIPROCKET_DEFAULT_PINCODE', '600001')

# ── Site ──────────────────────────────────────────────────────────────────────
SITE_DOMAIN = os.environ.get('SITE_DOMAIN', 'localhost:8000')

# ── Security headers ─────────────────────────────────────────────────────────
SESSION_COOKIE_HTTPONLY     = True            # JS cannot read the session cookie
SESSION_COOKIE_SAMESITE     = 'Lax'
CSRF_COOKIE_SAMESITE        = 'Lax'
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS             = 'DENY'

# CSRF trusted origins — required by Django 4+ for HTTPS POST. Built from
# ALLOWED_HOSTS (a leading-dot wildcard host → https://*.domain), plus an
# optional comma-separated env override (DJANGO_CSRF_TRUSTED_ORIGINS).
def _csrf_origin(h):
    return f'https://*{h}' if h.startswith('.') else f'https://{h}'

CSRF_TRUSTED_ORIGINS = [
    _csrf_origin(h) for h in ALLOWED_HOSTS if h not in ('localhost', '127.0.0.1', '*')
]
_extra_csrf = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS += [o.strip() for o in _extra_csrf.split(',') if o.strip()]

# ── Production-only (HTTPS) hardening ────────────────────────────────────────
if not DEBUG:
    # Railway terminates TLS at its edge proxy — without this, SECURE_SSL_REDIRECT
    # loops forever and request.is_secure() reports False.
    SECURE_PROXY_SSL_HEADER        = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS            = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD            = True
    SECURE_SSL_REDIRECT            = True
    # The platform healthcheck hits /healthz over plain HTTP on the internal
    # network (no X-Forwarded-Proto), so exempt it from the http->https redirect
    # or it gets a 301 and the deploy is marked unhealthy.
    SECURE_REDIRECT_EXEMPT         = [r'^healthz$']
    SESSION_COOKIE_SECURE          = True
    CSRF_COOKIE_SECURE             = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
